#include <vector>

void bindParameters()
{
	parameter stepSizeParameter;
	stepSizeParameter.name = "stepSize";
	stepSizeParameter.type = 'f';
	stepSizeParameter.variable = &stepSize;
	parameters.push_back(stepSizeParameter);
	parameter stepHeightParameter;
	stepHeightParameter.name = "stepHeight";
	stepHeightParameter.type = 'f';
	stepHeightParameter.variable = &stepHeight;
	parameters.push_back(stepHeightParameter);
	parameter stepAngleParameter;
	stepAngleParameter.name = "stepAngle";
	stepAngleParameter.type = 'f';
	stepAngleParameter.variable = &stepAngle;
	parameters.push_back(stepAngleParameter);
	parameter thicknessParameter;
	thicknessParameter.name = "thickness";
	thicknessParameter.type = 'f';
	thicknessParameter.variable = &thickness;
	parameters.push_back(thicknessParameter);
	parameter railingHOffsetParameter;
	railingHOffsetParameter.name = "railingHOffset";
	railingHOffsetParameter.type = 'f';
	railingHOffsetParameter.variable = &railingHOffset;
	parameters.push_back(railingHOffsetParameter);
	parameter railingVOffsetParameter;
	railingVOffsetParameter.name = "railingVOffset";
	railingVOffsetParameter.type = 'f';
	railingVOffsetParameter.variable = &railingVOffset;
	parameters.push_back(railingVOffsetParameter);
	parameter railingWidthParameter;
	railingWidthParameter.name = "railingWidth";
	railingWidthParameter.type = 'f';
	railingWidthParameter.variable = &railingWidth;
	parameters.push_back(railingWidthParameter);
	parameter railingThicknessParameter;
	railingThicknessParameter.name = "railingThickness";
	railingThicknessParameter.type = 'f';
	railingThicknessParameter.variable = &railingThickness;
	parameters.push_back(railingThicknessParameter);
	parameter railingPipeEachXStepsParameter;
	railingPipeEachXStepsParameter.name = "railingPipeEachXSteps";
	railingPipeEachXStepsParameter.type = 'i';
	railingPipeEachXStepsParameter.variable = &railingPipeEachXSteps;
	parameters.push_back(railingPipeEachXStepsParameter);
	parameter railingPipeHeightParameter;
	railingPipeHeightParameter.name = "railingPipeHeight";
	railingPipeHeightParameter.type = 'f';
	railingPipeHeightParameter.variable = &railingPipeHeight;
	parameters.push_back(railingPipeHeightParameter);
	parameter railingPipeResParameter;
	railingPipeResParameter.name = "railingPipeRes";
	railingPipeResParameter.type = 'i';
	railingPipeResParameter.variable = &railingPipeRes;
	parameters.push_back(railingPipeResParameter);
	parameter railingPipeRadiusParameter;
	railingPipeRadiusParameter.name = "railingPipeRadius";
	railingPipeRadiusParameter.type = 'f';
	railingPipeRadiusParameter.variable = &railingPipeRadius;
	parameters.push_back(railingPipeRadiusParameter);
	parameter railingPipeTwistAngleParameter;
	railingPipeTwistAngleParameter.name = "railingPipeTwistAngle";
	railingPipeTwistAngleParameter.type = 'f';
	railingPipeTwistAngleParameter.variable = &railingPipeTwistAngle;
	parameters.push_back(railingPipeTwistAngleParameter);
	parameter railingPipePolygonSidesParameter;
	railingPipePolygonSidesParameter.name = "railingPipePolygonSides";
	railingPipePolygonSidesParameter.type = 'i';
	railingPipePolygonSidesParameter.variable = &railingPipePolygonSides;
	parameters.push_back(railingPipePolygonSidesParameter);
}
